services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_PORT=5432
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_NAME=nestjs_db
        depends_on:
            - postgres
        volumes:
            - ./backend:/app
            - /app/node_modules
        command: pnpm start:dev

    postgres:
        image: postgres:16
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=nestjs_db
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3001:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
            - loki
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"

    loki:
        image: grafana/loki:latest
        ports:
            - "3100:3100"
        volumes:
            - loki_data:/loki
        command: -config.file=/etc/loki/local-config.yaml

    promtail:
        image: grafana/promtail:latest
        volumes:
            - ./promtail/promtail-config.yml:/etc/promtail/config.yml
            - /var/log:/var/log
        command: -config.file=/etc/promtail/config.yml

volumes:
    postgres_data:
    grafana_data:
    prometheus_data:
    loki_data:
