{
 "title": "Node.js Application Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node.js Memory Usage",
   "type": "timeseries",
   "description": "Node.js process memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=\"backend\"}",
     "legendFormat": "Heap Size Total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"backend\"}",
     "legendFormat": "Heap Size Used"
    }
   ]
  },
  {
   "title": "Node.js CPU Usage",
   "type": "timeseries",
   "description": "Node.js CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_user_seconds_total{job=\"backend\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "description": "Application logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"container_logs\"} |= ``"
    }
   ]
  }
 ]
}