server:
    http_listen_port: 9080

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: containers
      static_configs:
          - targets:
                - localhost
            labels:
                job: container_logs
                __path__: /var/log/containers/*.log

    - job_name: system
      static_configs:
          - targets:
                - localhost
            labels:
                job: system_logs
                __path__: /var/log/*.log
