name: Coverage

on: [push, pull_request]

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  cd backend
                  npm install
            - name: Run tests with coverage
              run: |
                  cd backend
                  npm run test:cov
            - name: Upload coverage
              uses: actions/upload-artifact@v4
              with:
                  name: coverage
                  path: backend/coverage
            - name: Finish
              run: |
                  echo "Coverage report uploaded successfully 🚀"
