name: PR Congratulation

permissions:
    pull-requests: write

on:
    pull_request:
        types: [opened]

jobs:
    congratulation:
        runs-on: ubuntu-latest
        steps:
            - name: Congratulation
              uses: actions/github-script@v6
              with:
                script: |
                    github.rest.issues.createComment({ 
                            issue_number: context.issue.number, 
                            owner: context.repo.owner, 
                            repo: context.repo.repo, 
                            body: '👋 Thanks for the PR! The automated tests will run shortly. 🎉'
                        })